apiVersion: apps/v1
kind: Deployment
metadata:
  name: sktrading-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sktrading
  template:
    metadata:
      labels:
        app: sktrading
    spec:
      containers:
        - name: sktrading-container
    image: sktrading:v1
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 250m

---
apiVersion: v1
kind: Service
metadata:
  name: sktrading-service
spec:
  type: NodePort
  selector:
    app: sktrading
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

